# Generated by Django 5.2.17 on 2026-09-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_carmodel_dealer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='make',
            new_name='car_make',
        ),
    ]
